export { default as Navbar } from './Navbar'
export { default as HeroSection } from './HeroSection'
export { default as ServiceCard } from './ServiceCard'
export { default as PackageCard } from './PackageCard'
export { default as TestimonialCard } from './TestimonialCard'
export { default as ContactForm } from './ContactForm'
export { default as StatsSection } from './StatsSection'
export { default as FeatureSection } from './FeatureSection'
export { default as CTAButton } from './CTAButton'
export { default as WhatsAppButton } from './WhatsAppButton'
export { FloatingActionButtons } from './WhatsAppButton'
export { default as TrustBadge } from './TrustBadge'

// New Landing Page Sections
export { default as HeroLandingSection } from './HeroLandingSection'
export { default as StatsLandingSection } from './StatsLandingSection'
export { default as ServicesLandingSection } from './ServicesLandingSection'
export { default as FeaturesLandingSection } from './FeaturesLandingSection'
export { default as GalleryLandingSection } from './GalleryLandingSection'
export { default as TestimonialsSection } from './TestimonialsSection'
export { default as CTALandingSection } from './CTALandingSection'
